### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iberezovchuk**

### CODE REVIEW

**Comment by iberezovchuk** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============

--------------

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============

--------------

**Comment by podarok** [comment]
retest this please

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============

--------------

**Comment by podarok** [comment]
retest this please

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============

--------------

**Comment by podarok** [comment]
retest this please

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============

--------------

**Comment by iberezovchuk** [comment]
Build comment file: 
--------------
===============
<strong>2</strong> Security Review: Security Review standard file http://188.166.10.81/build6/build_reports/SecurityReview.txt
<strong>2</strong> Security Review: Security Review standard file http://188.166.10.81/build6/build_reports/SecurityReview.txt
<strong>2</strong> Security Review: Security Review standard file http://188.166.10.81/build6/build_reports/SecurityReview.txt
<strong>2</strong> Security Review: Security Review standard file http://188.166.10.81/build6/build_reports/SecurityReview.txt
Build site installed at http://188.166.10.81/build6
Behat tests: standard file http://188.166.10.81/build6/build_reports/report.html

--------------

**Pull request merged**
